# Generated by Django 2.2 on 2019-05-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desktop',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
